{
 "title": "Multilog",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Basics",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "multilogger",
     "query": "SELECT \"ip\", \"responseTime\", \"host\", \"statusCode\", \"statusMessage\", \"method\", \"url\", \"path\", \"body\" FROM \"multilogger\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" }
      ],
      [
       { "params": [ "responseTime" ], "type": "field" }
      ],
      [
       { "params": [ "host" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Number of requests" }
   ],
   "targets": [
    {
     "alias": "Number of Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "number_of_requests",
     "query": "SELECT sum(\"requests\") FROM \"number_of_requests\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "1xx Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "number_of_requests",
     "select": [
      [
       { "params": [ "amountOf1xx" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "2xx Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "number_of_requests",
     "select": [
      [
       { "params": [ "amountOf2xx" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "3xx Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "number_of_requests",
     "select": [
      [
       { "params": [ "amountOf3xx" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "4xx Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "number_of_requests",
     "select": [
      [
       { "params": [ "amountOf4xx" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "5xx Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "number_of_requests",
     "select": [
      [
       { "params": [ "amountOf5xx" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "errorStack" ], "type": "tag" },
      { "params": [ "errorMessage" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "multilogger",
     "query": "SELECT \"host\", \"statusCode\", \"path\", \"url\", \"body\", \"auth\", \"params\", \"query\" FROM \"multilogger\" WHERE (\"statusCode\" =~ /^([45])/) AND $timeFilter GROUP BY \"errorStack\", \"errorMessage\"  order by desc limit 1;",
     "select": [
      [
       { "params": [ "host" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statusCode", "operator": "<>", "value": "200" }
     ]
    }
   ]
  },
  {
   "title": "Database Metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "databaseMetrics",
     "query": "SELECT timing FROM \"databaseMetrics\" GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "timing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 21, "w": 9, "x": 0, "y": 30 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "geohash" ], "type": "tag" }
     ],
     "measurement": "multilogger",
     "query": "SELECT sum(\"requests\") AS \"metric\" FROM \"multilogger\" WHERE (\"geohash\"::tag != '' AND \"geohash\"::tag != '7zzzzzzzz' AND \"geohash\"::tag != ' ' ) AND $timeFilter GROUP BY \"geohash\", \"country\"",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "geohash", "operator": "=", "value": "9wvfgzurfzb" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 30 },
   "yaxes": [
    { "format": "decbytes", "label": "Usage" }
   ],
   "targets": [
    {
     "alias": "$tag_osHost | Total memory: $tag_totalMemory GB",
     "groupBy": [
      { "params": [ "osHost" ], "type": "tag" },
      { "params": [ "totalMemory" ], "type": "tag" }
     ],
     "measurement": "multilogger",
     "select": [
      [
       { "params": [ "memoryUsage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 41 },
   "yaxes": [
    { "format": "percent", "label": "Usage" }
   ],
   "targets": [
    {
     "alias": "$tag_osHost",
     "groupBy": [
      { "params": [ "osHost" ], "type": "tag" }
     ],
     "measurement": "multilogger",
     "select": [
      [
       { "params": [ "cpuUsage" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}